#!/bin/bash
# ================================================================
# ZKLR HPC Grid Sweep — rigorous, self-contained.
#
# Pull the repo on the HPC node and run:
#     chmod +x run_hpc_sweep.sh
#     ./run_hpc_sweep.sh
#
# Produces (machine-readable, no fragile log parsing):
#   results/hpc_sweep.csv          one row per (batch, workers, repetition)
#   results/constraint_scaling.csv constraints vs batch at the dataset's features
# Then run the analysis to get medians + heatmap + cost-model fit:
#   python3 scripts/analyze_hpc_sweep.py
#
# Override any setting via environment variables, e.g.:
#   REPS=10 BATCH_SIZES="10 20 40 80" WORKER_COUNTS="1 4 8 16 32 64" ./run_hpc_sweep.sh
#   DATASET=data/test_3000.csv WEIGHTS_FILE=data/model_weights.txt ./run_hpc_sweep.sh
# ================================================================
set -euo pipefail

# ── Config (env-overridable) ──────────────────────────────────
DATASET="${DATASET:-data/credit_test.csv}"          # real finance set: 9000 samples, 23 features
WEIGHTS_FILE="${WEIGHTS_FILE:-data/credit_weights.txt}"
MODE="${MODE:-label}"
REPS="${REPS:-10}"                                  # N repetitions per config (median ± std)
read -r -a BATCH_SIZES <<< "${BATCH_SIZES:-10 20 40 80}"
read -r -a WORKER_COUNTS <<< "${WORKER_COUNTS:-1 4 8 16 32 64}"
CSV="${CSV:-results/hpc_sweep.csv}"

# ── Derive weights/bias/features from the weights file + dataset ──
if [[ ! -f "$WEIGHTS_FILE" ]]; then
  echo "ERROR: weights file $WEIGHTS_FILE not found."
  echo "Real datasets are generated by: python3 scripts/prepare_real_datasets.py"
  exit 1
fi
WEIGHTS=$(grep -i '^Weights:' "$WEIGHTS_FILE" | cut -d: -f2 | tr -d ' ')
BIAS=$(grep -i '^Bias:' "$WEIGHTS_FILE" | cut -d: -f2 | tr -d ' ')
FEATURES=$(head -1 "$DATASET" | awk -F, '{print NF-1}')

CPUS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

echo "=================================================="
echo "  ZKLR HPC Grid Sweep"
echo "  dataset=$DATASET  features=$FEATURES  mode=$MODE"
echo "  batches=[${BATCH_SIZES[*]}]  workers=[${WORKER_COUNTS[*]}]  reps=$REPS"
echo "  detected CPUs: $CPUS"
echo "=================================================="

mkdir -p results bin

# Build ONCE so per-run `go run` recompilation does not pollute timings.
echo "[build] compiling batch_predict + constraint_scan..."
go build -o bin/batch_predict ./cmd/batch_predict
go build -o bin/constraint_scan ./cmd/constraint_scan

# Constraint scaling at the matching feature count (compile-only, fast) so the
# cost model is internally consistent with the timing sweep.
echo "[scan] constraints vs batch (features=$FEATURES)..."
./bin/constraint_scan -features="$FEATURES" -mode="$MODE" \
  -batches="$(IFS=,; echo "${BATCH_SIZES[*]}")" \
  -out=results/constraint_scaling.csv >/dev/null 2>&1 || true

# Fresh CSV (header written by the program on first append).
rm -f "$CSV"

for B in "${BATCH_SIZES[@]}"; do
  # Warm the key cache once per batch size (cold setup is recorded inside
  # setup_seconds; subsequent reps are warm — separable in analysis).
  echo "[warm] batch=$B (one-time setup)..."
  ./bin/batch_predict -dataset="$DATASET" -weights="$WEIGHTS" -bias="$BIAS" \
    -batch="$B" -workers="${WORKER_COUNTS[0]}" -mode="$MODE" >/dev/null 2>&1 || true

  for W in "${WORKER_COUNTS[@]}"; do
    if [[ "$W" -gt "$CPUS" ]]; then
      echo "[skip] workers=$W exceeds CPUs=$CPUS"
      continue
    fi
    for ((run=1; run<=REPS; run++)); do
      printf "[run] batch=%-3s workers=%-3s rep=%-2s ... " "$B" "$W" "$run"
      ./bin/batch_predict \
        -dataset="$DATASET" -weights="$WEIGHTS" -bias="$BIAS" \
        -batch="$B" -workers="$W" -mode="$MODE" \
        -csv="$CSV" -run="$run" >/dev/null 2>&1
      WALL=$(tail -1 "$CSV" | awk -F, '{print $13}')
      echo "wall/sample=${WALL}s"
    done
  done
done

echo "=================================================="
echo " Sweep complete → $CSV"
echo " Analyze:  python3 scripts/analyze_hpc_sweep.py --csv $CSV"
echo " Then commit results/ and push so you can pull them back."
echo "=================================================="
