// cmd/evm_export — Generates the on-chain verification artifacts from a
// proof-export directory (produced by `batch_predict -export-proofs=<dir>`):
//
//	contracts/src/PlonkVerifier.sol   — gnark's PLONK verifier for this VK
//	contracts/test/ZKLRFixtures.sol   — real proofs + public inputs as Solidity
//	                                    fixtures for `forge test --gas-report`
//
// Public input layout (BatchLabelCircuit field order):
//
//	[ X[0][0..F-1], ..., X[B-1][0..F-1], Label[0..B-1], Commitment ]
//
// The commitment is always the LAST public input; the wrapper contract pins it.
//
// Usage:
//
//	go run ./cmd/evm_export -dir=results/proofs -out=contracts
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/consensys/gnark-crypto/ecc"
	fr "github.com/consensys/gnark-crypto/ecc/bn254/fr"
	"github.com/consensys/gnark/backend/plonk"
	plonkbn254 "github.com/consensys/gnark/backend/plonk/bn254"
	"github.com/consensys/gnark/backend/witness"

	"github.com/santhoshcheemala/ZKLR/prover"
)

func main() {
	dir := flag.String("dir", "", "proof-export directory (vk.key, batch_*.proof, batch_*.pubw)")
	out := flag.String("out", "contracts", "contracts directory to write into")
	maxBatches := flag.Int("max-fixtures", 3, "number of batches to embed as test fixtures")
	flag.Parse()

	if *dir == "" {
		fmt.Fprintln(os.Stderr, "Usage: evm_export -dir=<proof export dir> [-out=contracts]")
		os.Exit(2)
	}

	// ─── Verifier contract from VK ───────────────────────
	vk, err := prover.LoadVerificationKey(filepath.Join(*dir, "vk.key"))
	if err != nil {
		fail("load vk: %v", err)
	}

	srcDir := filepath.Join(*out, "src")
	testDir := filepath.Join(*out, "test")
	for _, d := range []string{srcDir, testDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			fail("mkdir %s: %v", d, err)
		}
	}

	verifierPath := filepath.Join(srcDir, "PlonkVerifier.sol")
	vf, err := os.Create(verifierPath)
	if err != nil {
		fail("create %s: %v", verifierPath, err)
	}
	if err := vk.ExportSolidity(vf); err != nil {
		fail("export solidity verifier: %v", err)
	}
	vf.Close()
	fmt.Printf("Wrote %s\n", verifierPath)

	// ─── Fixtures from proofs + public witnesses ─────────
	proofFiles, _ := filepath.Glob(filepath.Join(*dir, "batch_*.proof"))
	if len(proofFiles) == 0 {
		fail("no batch_*.proof files in %s", *dir)
	}
	sort.Strings(proofFiles)
	if len(proofFiles) > *maxBatches {
		proofFiles = proofFiles[:*maxBatches]
	}

	var sb strings.Builder
	sb.WriteString("// SPDX-License-Identifier: MIT\n")
	sb.WriteString("// Code generated by cmd/evm_export from real ZKLR proofs. DO NOT EDIT.\n")
	sb.WriteString("pragma solidity ^0.8.0;\n\n")
	sb.WriteString("library ZKLRFixtures {\n")

	var commitment string
	for i, pf := range proofFiles {
		proofHex, inputs, err := loadFixture(pf, strings.TrimSuffix(pf, ".proof")+".pubw")
		if err != nil {
			fail("fixture %s: %v", pf, err)
		}
		commitment = inputs[len(inputs)-1] // last public input by circuit layout

		fmt.Fprintf(&sb, "    function proof%d() internal pure returns (bytes memory) {\n", i)
		fmt.Fprintf(&sb, "        return hex\"%s\";\n    }\n\n", proofHex)

		fmt.Fprintf(&sb, "    function publicInputs%d() internal pure returns (uint256[] memory pi) {\n", i)
		fmt.Fprintf(&sb, "        pi = new uint256[](%d);\n", len(inputs))
		for j, v := range inputs {
			fmt.Fprintf(&sb, "        pi[%d] = %s;\n", j, v)
		}
		sb.WriteString("    }\n\n")
	}

	fmt.Fprintf(&sb, "    uint256 internal constant FIXTURE_COUNT = %d;\n\n", len(proofFiles))
	fmt.Fprintf(&sb, "    function modelCommitment() internal pure returns (uint256) {\n        return %s;\n    }\n", commitment)
	sb.WriteString("}\n")

	fixturePath := filepath.Join(testDir, "ZKLRFixtures.sol")
	if err := os.WriteFile(fixturePath, []byte(sb.String()), 0o644); err != nil {
		fail("write fixtures: %v", err)
	}
	fmt.Printf("Wrote %s (%d fixture(s))\n", fixturePath, len(proofFiles))
	fmt.Printf("Model commitment (last public input): %s\n", commitment)
	fmt.Println("\nNext: cd contracts && forge install foundry-rs/forge-std && forge test --gas-report")
}

// loadFixture returns the Solidity-marshalled proof (hex, no 0x) and the
// public inputs as decimal strings.
func loadFixture(proofPath, pubwPath string) (string, []string, error) {
	// Proof: gnark binary → MarshalSolidity byte layout
	proof := plonk.NewProof(ecc.BN254)
	if err := readInto(proofPath, proof.(io.ReaderFrom)); err != nil {
		return "", nil, fmt.Errorf("read proof: %w", err)
	}
	bnProof, ok := proof.(*plonkbn254.Proof)
	if !ok {
		return "", nil, fmt.Errorf("unexpected proof type %T", proof)
	}
	proofHex := fmt.Sprintf("%x", bnProof.MarshalSolidity())

	// Public witness → uint256 decimal strings
	pubWitness, err := witness.New(ecc.BN254.ScalarField())
	if err != nil {
		return "", nil, err
	}
	if err := readInto(pubwPath, pubWitness); err != nil {
		return "", nil, fmt.Errorf("read public witness: %w", err)
	}
	vec, ok := pubWitness.Vector().(fr.Vector)
	if !ok {
		return "", nil, fmt.Errorf("unexpected witness vector type %T", pubWitness.Vector())
	}
	inputs := make([]string, len(vec))
	for i := range vec {
		inputs[i] = vec[i].String()
	}
	return proofHex, inputs, nil
}

func readInto(path string, dst io.ReaderFrom) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = dst.ReadFrom(f)
	return err
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
