// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {ZKLRBatchVerifier} from "../src/ZKLRBatchVerifier.sol";
import {ZKLRFixtures} from "./ZKLRFixtures.sol";

/// Gas-measured verification of real ZKLR proofs (fixtures generated by
/// cmd/evm_export from actual prover output).
///
/// Run: forge test --gas-report -vv
contract ZKLRVerifierTest is Test {
    ZKLRBatchVerifier verifier;

    function setUp() public {
        verifier = new ZKLRBatchVerifier(ZKLRFixtures.modelCommitment());
    }

    /// Valid proof for the pinned model must verify.
    function test_VerifyValidBatch() public view {
        bool ok = verifier.verifyBatch(ZKLRFixtures.proof0(), ZKLRFixtures.publicInputs0());
        assertTrue(ok, "valid proof rejected");
    }

    /// Gas measurement entry point (non-view so gas-report captures it).
    function test_Gas_VerifyBatch() public {
        bool ok = verifier.verifyBatch(ZKLRFixtures.proof0(), ZKLRFixtures.publicInputs0());
        assertTrue(ok);
    }

    /// A tampered public input (flipped label) must not verify.
    function test_RejectTamperedLabel() public view {
        uint256[] memory pi = ZKLRFixtures.publicInputs0();
        // Flip the first label (labels sit between the features and the
        // trailing commitment; flipping any non-commitment input suffices).
        uint256 labelIdx = pi.length - 2;
        pi[labelIdx] = 1 - pi[labelIdx];

        bool ok;
        try verifier.verifyBatch(ZKLRFixtures.proof0(), pi) returns (bool r) {
            ok = r;
        } catch {
            ok = false;
        }
        assertFalse(ok, "tampered label accepted");
    }

    /// A proof presented under a different model commitment must revert.
    function test_RejectWrongCommitment() public {
        uint256[] memory pi = ZKLRFixtures.publicInputs0();
        pi[pi.length - 1] = pi[pi.length - 1] ^ 1;

        vm.expectRevert(
            abi.encodeWithSelector(
                ZKLRBatchVerifier.WrongModelCommitment.selector,
                pi[pi.length - 1],
                ZKLRFixtures.modelCommitment()
            )
        );
        verifier.verifyBatch(ZKLRFixtures.proof0(), pi);
    }

    /// A corrupted proof must not verify.
    function test_RejectCorruptedProof() public view {
        bytes memory proof = ZKLRFixtures.proof0();
        proof[100] = bytes1(uint8(proof[100]) ^ 0x42);

        bool ok;
        try verifier.verifyBatch(proof, ZKLRFixtures.publicInputs0()) returns (bool r) {
            ok = r;
        } catch {
            ok = false;
        }
        assertFalse(ok, "corrupted proof accepted");
    }
}
